### ISSUE TITLE
lvis_v0.5_train_rare.json

### ISSUE THREAD

**Issue by qinzhengmei** [ucbdrive/few-shot-object-detection#101]
Thank you for your excellent work!
Since lvis_v0.5 is not allowed to be downloaded on the official website, I directly used lvis_v1.0. Instead of modifying the code, I directly changed the filename of lvis_v0.5.
I tried to run
python3 -m tools.train_net --num-gpus 1 \
        --config-file configs/LVIS-detection/faster_rcnn_R_50_FPN_fc_novel.yaml \
        --opts MODEL.WEIGHTS checkpoints/lvis/faster_rcnn/faster_rcnn_R_50_FPN_base_nomask2/model_reset_remove.pth

Error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/few-shot-object-detection/tools/train_net.py", line 113, in <module>
    args=(args,),
  File "/root/fsdet/lib/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "/root/few-shot-object-detection/tools/train_net.py", line 99, in main
    trainer = Trainer(cfg)
  File "/root/few-shot-object-detection/fsdet/engine/defaults.py", line 308, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/root/few-shot-object-detection/fsdet/engine/defaults.py", line 493, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/root/fsdet/lib/python3.6/site-packages/detectron2/config/config.py", line 201, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/root/fsdet/lib/python3.6/site-packages/detectron2/config/config.py", line 236, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/root/fsdet/lib/python3.6/site-packages/detectron2/data/build.py", line 307, in _train_loader_from_config
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/root/fsdet/lib/python3.6/site-packages/detectron2/data/build.py", line 220, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/root/fsdet/lib/python3.6/site-packages/detectron2/data/build.py", line 220, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/root/fsdet/lib/python3.6/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/root/few-shot-object-detection/fsdet/data/meta_lvis.py", line 129, in <lambda>
    lambda: load_filtered_lvis_json(json_file, image_root, metadata, name),
  File "/root/few-shot-object-detection/fsdet/data/meta_lvis.py", line 55, in load_filtered_lvis_json
    assert global_cfg.MODEL.ROI_HEADS.NUM_CLASSES == len(
  File "/root/fsdet/lib/python3.6/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: MODEL

How I can solve thie error?

**Comment by xinw1012** [comment]
Hey sorry for the delayed response. It looks like a data registration error.  The number of categories in LVIS v0.5 and v1.0 is different so the data registration is problematic. You can add another data registration for lvis 1.0. 

You are very welcome to contribute a PR if you have time.  We will put this on the to-do list to add support for this. 

Thanks!

**Comment by Z-MU-Z** [comment]
I meet the same problem , you need to change from detectron2.config import global_cfg --> from fsdet.config import global_cfg
