### ISSUE TITLE
I cannot download pretrained model succesesfully.

### ISSUE THREAD

**Issue by jsxapril** [ucbdrive/few-shot-object-detection#14]
Thank you for your good work.
 When I try to use demo for a test, I find the 'mode_final.pth' cannot be download succesesfully. 
Could you provide these files from a other websites or google.dirve?

Thank you very much. Best wishes!

**Comment by xinw1012** [comment]
Thanks for your interest! 

The trained models can be found in the tables at https://github.com/ucbdrive/few-shot-object-detection/blob/master/MODEL_ZOO.md
I just tried downloading them and it worked on my side.  Can you try again? If it still doesn't work, let us know. We can try to put them on Google drive or One drive later.  Hope this helps!

**Comment by jsxapril** [comment]
I still cannot down the  trained models. The following is the massege when I downloaded them by "model = model_zoo.get(
...    "COCO-detection/faster_rcnn_R_101_FPN_ft_all_1shot.yaml", trained=True)
": 
froze backbone parameters
froze proposal generator parameters
froze roi_box_head parameters
model_final.pth:   8%|█▌                  | 19.7M/245M [10:18<1:57:46, 31.9kB/s]
Failed to download http://dl.yf.io/fs-det/models/coco/tfa_cos_1shot/model_final.pth
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/data/public/retail/jishuangxi/Alg-test/Git/few-shot-object-detection-master/fsdet/model_zoo/model_zoo.py", line 179, in get
    DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 100, in load
    path = PathManager.get_local_path(path)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/file_io.py", line 620, in get_local_path
    path, **kwargs
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/file_io.py", line 495, in _get_local_path
    cached = download(path, dirname, filename=filename)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/download.py", line 58, in download
    tmp, _ = request.urlretrieve(url, filename=tmp, reporthook=hook(t))
  File "/root/anaconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 19710913 out of 245166210 bytes>

How can I get them?

**Comment by jsxapril** [comment]
> Thanks for your interest!
> 
> The trained models can be found in the tables at https://github.com/ucbdrive/few-shot-object-detection/blob/master/MODEL_ZOO.md
> I just tried downloading them and it worked on my side. Can you try again? If it still doesn't work, let us know. We can try to put them on Google drive or One drive later. Hope this helps!

I still cannot down the trained models. The following is the massege when I downloaded them by "model = model_zoo.get(
... "COCO-detection/faster_rcnn_R_101_FPN_ft_all_1shot.yaml", trained=True)
":
froze backbone parameters
froze proposal generator parameters
froze roi_box_head parameters
model_final.pth: 8%|█▌ | 19.7M/245M [10:18<1:57:46, 31.9kB/s]
Failed to download http://dl.yf.io/fs-det/models/coco/tfa_cos_1shot/model_final.pth
Traceback (most recent call last):
File "", line 2, in
File "/opt/data/public/retail/jishuangxi/Alg-test/Git/few-shot-object-detection-master/fsdet/model_zoo/model_zoo.py", line 179, in get
DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)
File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 100, in load
path = PathManager.get_local_path(path)
File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/file_io.py", line 620, in get_local_path
path, **kwargs
File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/file_io.py", line 495, in _get_local_path
cached = download(path, dirname, filename=filename)
File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/fvcore/common/download.py", line 58, in download
tmp, _ = request.urlretrieve(url, filename=tmp, reporthook=hook(t))
File "/root/anaconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 288, in urlretrieve
% (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 19710913 out of 245166210 bytes>

How can I get them?

**Comment by dnth** [comment]
The download links for the models isnt working at the moment. Is there any alternative download link?

**Comment by fyu** [comment]
@dnth The site http://dl.yf.io/fs-det/ is working for me now outside the domain of the server.

**Comment by dnth** [comment]
Ahh yes! This works! Thanks @fyu
