### ISSUE TITLE
ERROR  in from fsdet import model_zoo

### ISSUE THREAD

**Issue by WumingzheAI** [ucbdrive/few-shot-object-detection#154]

**Comment by WumingzheAI** [comment]
>>> from fsdet import model_zoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mz/few-shot-object-detection/fsdet/model_zoo/__init__.py", line 6, in <module>
    from .model_zoo import get, get_checkpoint_url, get_config_file
  File "/home/mz/few-shot-object-detection/fsdet/model_zoo/model_zoo.py", line 8, in <module>
    from fsdet.modeling import build_model
  File "/home/mz/few-shot-object-detection/fsdet/modeling/__init__.py", line 1, in <module>
    from .meta_arch import (
  File "/home/mz/few-shot-object-detection/fsdet/modeling/meta_arch/__init__.py", line 4, in <module>
    from .rcnn import GeneralizedRCNN, ProposalNetwork
  File "/home/mz/few-shot-object-detection/fsdet/modeling/meta_arch/rcnn.py", line 4, in <module>
    from detectron2.modeling.backbone import build_backbone
  File "/home/mz/anaconda3/envs/fsdet/lib/python3.6/site-packages/detectron2/modeling/__init__.py", line 2, in <module>
    from detectron2.layers import ShapeSpec
  File "/home/mz/anaconda3/envs/fsdet/lib/python3.6/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/mz/anaconda3/envs/fsdet/lib/python3.6/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
