### ISSUE TITLE
The problem of checkpoints

### ISSUE THREAD

**Issue by sxu-dzw** [ucbdrive/few-shot-object-detection#169]
[03/07 16:46:42 fvcore.common.checkpoint]: [Checkpointer] Loading from checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_surgery.pth ...
Traceback (most recent call last):
  File "/root/data/anaconda3/envs/fsdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/data/anaconda3/envs/fsdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/data/few-shot-object-detection-master/tools/train_net.py", line 119, in <module>
    args=(args,),
  File "/root/data/anaconda3/envs/fsdet/lib/python3.7/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "/root/data/few-shot-object-detection-master/tools/train_net.py", line 106, in main
    trainer.resume_or_load(resume=args.resume)
  File "/root/data/few-shot-object-detection-master/fsdet/engine/defaults.py", line 345, in resume_or_load
    self.cfg.MODEL.WEIGHTS, resume=resume
  File "/root/data/anaconda3/envs/fsdet/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/root/data/anaconda3/envs/fsdet/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_surgery.pth not found!

**Comment by hansgreen4396** [comment]
你解决了吗这个问题

**Comment by sxu-dzw** [comment]
No.



在 2023-05-09 17:47:27，"hansgreen4396" ***@***.***> 写道：

你解决了吗这个问题

**Comment by wangchao6083** [comment]
您解决这个问题了吗，我也遇到了同样的问题
