### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by 1786939789** [ucbdrive/few-shot-object-detection#58]
I have followed the instructions to install the dependencies. But when I build FsDet, there was a RuntimeError: Error compiling objects for extension.

My environment：
- CUDA 10.2
- pytorch 1.5.0
- python 3.7.7
- GCC 7.5.0

Error:
Traceback (most recent call last):
  File "setup.py", line 114, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/usr0/home/zhiqic/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by bjditto1221** [comment]
Had a similar issue.  torch.cuda.is_available() returns true even if your pytorch version doesn't support an older gpu.  So, removing the code from line 32-41 in setup.py worked for me.

**Comment by hjraad** [comment]
@thomasehuang : facing the same issue, any idea?

**Comment by hjraad** [comment]
@bjditto1221 : lines 32-41? or 32 to 46?

**Comment by xinw1012** [comment]
Could you try to build the code with CUDA 10.0?  There might be some issues with CUDA 10.2.  We are working on upgrading the code and remove the detectron2 dependencies. Stay tuned.

**Comment by hjamalirad** [comment]
I managed to fix it following some hint on the internet regarding cuBLAS. Nonetheless, an upgrade is more than welcome.

**Comment by bjditto1221** [comment]
> @bjditto1221 : lines 32-41? or 32 to 46?

@hjraad my bad it is 32-46.  I should also mention this is just a hack to get it to work with cpu only. if you need it to run on gpu you'll need to try the CUDA changes mentioned above.

**Comment by xinw1012** [comment]
The codebase has been upgraded. It should work for CUDA10.2 with Pytorch 1.6 now. The detectron2 version is now upgraded to v0.2.1.  Feel free to test the latest release and let us know if anything goes wrong. Thanks!

**Comment by chengyu0910** [comment]
@bjditto1221 it work for me too, thanks!
cuda: 10.2
pytorch: 1.6.0
python: 3.7.9
gcc: 5.4.0
