### ISSUE TITLE
Can't import model_zoo

### ISSUE THREAD

**Issue by abexultan** [ucbdrive/few-shot-object-detection#6]
When trying to import model_zoo as following:
```python
from fsdet import model_zoo
```
attribute error raises as:
```console
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from fsdet import model_zoo
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/model_zoo/__init__.py", line 7, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/model_zoo/model_zoo.py", line 182, in <module>
    model = get('COCO-detection/faster_rcnn_R_101_FPN_ft_all_1shot_unfreeze.yaml', True)
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/model_zoo/model_zoo.py", line 178, in get
    model = build_model(cfg)
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/modeling/meta_arch/build.py", line 18, in build_model
    return META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/modeling/meta_arch/rcnn.py", line 33, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.output_shape())
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/modeling/roi_heads/roi_heads.py", line 40, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/modeling/roi_heads/roi_heads.py", line 372, in __init__
    self._init_box_head(cfg)
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/modeling/roi_heads/roi_heads.py", line 404, in _init_box_head
    self.cls_agnostic_bbox_reg,
  File "/media/kist/DATA_2/few-shot-object-detection/fsdet/modeling/roi_heads/fast_rcnn.py", line 392, in __init__
    self.scale = global_cfg.MODEL.ROI_HEADS.COSINE_SCALE
  File "/home/kist/few-shot-object-detection/fsdet/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: MODEL
```

**Comment by abexultan** [comment]
model_zoo.py contains unwanted code

**Comment by thomasehuang** [comment]
Thank you for pointing out this issue. This has been fixed in the most recent commit, so you should be able to use the model_zoo without issue.
