### ISSUE TITLE
running python demo.py

### ISSUE THREAD

**Issue by jtbarker** [ucbdrive/few-shot-object-detection#78]
Getting:

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from demo.predictor import VisualizationDemo
  File "/Users/jonbrkr/dvlp/few-shot-object-detection/demo/demo.py", line 10, in <module>
    from demo.predictor import VisualizationDemo
ModuleNotFoundError: No module named 'demo.predictor'; 'demo' is not a package

**Comment by pantment** [comment]
@jtbarker  How did you solve it?
