### ISSUE TITLE
ImageNet pretrained model not loaded

### ISSUE THREAD

**Issue by HeliosZhao** [ucbdrive/few-shot-object-detection#87]
Hi,

I train the base model but got the following error
the detectron2 pretrained model could not be loaded

```
[01/28 18:24:35 fvcore.common.checkpoint]: Loading checkpoint from detectron2://ImageNetPretrained/MSRA/R-101.pkl
Traceback (most recent call last):
  File "/home/fxyang/.conda/envs/detection/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fxyang/.conda/envs/detection/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fxyang/zyy/detection/code/few-shot-object-detection/tools/train_net.py", line 113, in <module>
    args=(args,),
  File "/home/fxyang/.conda/envs/detection/lib/python3.7/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "/home/fxyang/zyy/detection/code/few-shot-object-detection/tools/train_net.py", line 100, in main
    trainer.resume_or_load(resume=args.resume)
  File "/home/fxyang/zyy/detection/code/few-shot-object-detection/fsdet/engine/defaults.py", line 349, in resume_or_load
    self.cfg.MODEL.WEIGHTS, resume=resume
  File "/home/fxyang/.conda/envs/detection/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 198, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/fxyang/.conda/envs/detection/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 124, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-101.pkl not found!

```

So how can I fix this?

**Comment by davesie** [comment]
You can just manually download it [here](https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-101.pkl)

**Comment by HeliosZhao** [comment]
OK, it works.

Thanks, and I will close this issue.

**Comment by Guo-Zichen** [comment]
can you share the route of R-101.pkl?

**Comment by cmranieri** [comment]
> You can just manually download it [here](https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-101.pkl)

Where should I place it?

**Comment by CC012118** [comment]
> can you share the route of R-101.pkl?

You just need to download "R-101.pkl" from the link given above, and then change the "WEIGHTS" in the "faster_rcnn_R_101_FPN_base.yaml" to "path/to/R-101.pkl" in your computer. It works for me. Hope this will help you.
