### ISSUE TITLE
Error when trying to run Demo

### ISSUE THREAD

**Issue by ruohuali** [ucbdrive/few-shot-object-detection#91]
When running demo.demo.py, error
`AssertionError: Checkpoint fsdet://coco/tfa_cos_1shot/model_final.pth not found!
`
was reported. Is training mandatory for this repo or is there anywhere I can download the pretrained weights?
Thx for the help!

Whole terminal output:
`** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

[03/01 04:20:13 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-detection/faster_rcnn_R_101_FPN_ft_all_1shot.yaml', input=['input1.jpg', 'input2.jpg'], opts=['MODEL.WEIGHTS', 'fsdet://coco/tfa_cos_1shot/model_final.pth'], output=None, video_input=None, webcam=False)
froze backbone parameters
froze proposal generator parameters
froze roi_box_head parameters
[03/01 04:20:16 fvcore.common.checkpoint]: Loading checkpoint from fsdet://coco/tfa_cos_1shot/model_final.pth
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ruohuali/Desktop/few-shot-object-detection/demo/demo.py", line 81, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/ruohuali/Desktop/few-shot-object-detection/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/ruohuali/Desktop/few-shot-object-detection/fsdet/engine/defaults.py", line 220, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/ruohuali/smr-pyenv/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint fsdet://coco/tfa_cos_1shot/model_final.pth not found!
`

**Comment by scott-vsi** [comment]
fsdet:// defines a model as downloaded by fsdet & detectron2's model zoo. [MODEL_ZOO.md](https://github.com/ucbdrive/few-shot-object-detection/blob/model_zoo/docs/MODEL_ZOO.md) describes how to do this. However, I had a problem with that command. I fixed it like this: #97 [edited]

**Comment by scott-vsi** [comment]
Oops. I meant #97

**Comment by xinw1012** [comment]
Thanks, @scott-vsi! Closing the issue for now.
